// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.2
// source: category/v1/category.proto

package category

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllLevelOneRequest_Sort int32

const (
	GetAllLevelOneRequest_ASCENDING_UNSPECIFIED GetAllLevelOneRequest_Sort = 0
	GetAllLevelOneRequest_DESCENDING            GetAllLevelOneRequest_Sort = 1
)

// Enum value maps for GetAllLevelOneRequest_Sort.
var (
	GetAllLevelOneRequest_Sort_name = map[int32]string{
		0: "ASCENDING_UNSPECIFIED",
		1: "DESCENDING",
	}
	GetAllLevelOneRequest_Sort_value = map[string]int32{
		"ASCENDING_UNSPECIFIED": 0,
		"DESCENDING":            1,
	}
)

func (x GetAllLevelOneRequest_Sort) Enum() *GetAllLevelOneRequest_Sort {
	p := new(GetAllLevelOneRequest_Sort)
	*p = x
	return p
}

func (x GetAllLevelOneRequest_Sort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetAllLevelOneRequest_Sort) Descriptor() protoreflect.EnumDescriptor {
	return file_category_v1_category_proto_enumTypes[0].Descriptor()
}

func (GetAllLevelOneRequest_Sort) Type() protoreflect.EnumType {
	return &file_category_v1_category_proto_enumTypes[0]
}

func (x GetAllLevelOneRequest_Sort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetAllLevelOneRequest_Sort.Descriptor instead.
func (GetAllLevelOneRequest_Sort) EnumDescriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{3, 0}
}

type GetLevelTwoRequest_Sort int32

const (
	GetLevelTwoRequest_ASCENDING_UNSPECIFIED GetLevelTwoRequest_Sort = 0
	GetLevelTwoRequest_DESCENDING            GetLevelTwoRequest_Sort = 1
)

// Enum value maps for GetLevelTwoRequest_Sort.
var (
	GetLevelTwoRequest_Sort_name = map[int32]string{
		0: "ASCENDING_UNSPECIFIED",
		1: "DESCENDING",
	}
	GetLevelTwoRequest_Sort_value = map[string]int32{
		"ASCENDING_UNSPECIFIED": 0,
		"DESCENDING":            1,
	}
)

func (x GetLevelTwoRequest_Sort) Enum() *GetLevelTwoRequest_Sort {
	p := new(GetLevelTwoRequest_Sort)
	*p = x
	return p
}

func (x GetLevelTwoRequest_Sort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetLevelTwoRequest_Sort) Descriptor() protoreflect.EnumDescriptor {
	return file_category_v1_category_proto_enumTypes[1].Descriptor()
}

func (GetLevelTwoRequest_Sort) Type() protoreflect.EnumType {
	return &file_category_v1_category_proto_enumTypes[1]
}

func (x GetLevelTwoRequest_Sort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetLevelTwoRequest_Sort.Descriptor instead.
func (GetLevelTwoRequest_Sort) EnumDescriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{9, 0}
}

type GetLevelThreeRequest_Sort int32

const (
	GetLevelThreeRequest_ASCENDING_UNSPECIFIED GetLevelThreeRequest_Sort = 0
	GetLevelThreeRequest_DESCENDING            GetLevelThreeRequest_Sort = 1
)

// Enum value maps for GetLevelThreeRequest_Sort.
var (
	GetLevelThreeRequest_Sort_name = map[int32]string{
		0: "ASCENDING_UNSPECIFIED",
		1: "DESCENDING",
	}
	GetLevelThreeRequest_Sort_value = map[string]int32{
		"ASCENDING_UNSPECIFIED": 0,
		"DESCENDING":            1,
	}
)

func (x GetLevelThreeRequest_Sort) Enum() *GetLevelThreeRequest_Sort {
	p := new(GetLevelThreeRequest_Sort)
	*p = x
	return p
}

func (x GetLevelThreeRequest_Sort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetLevelThreeRequest_Sort) Descriptor() protoreflect.EnumDescriptor {
	return file_category_v1_category_proto_enumTypes[2].Descriptor()
}

func (GetLevelThreeRequest_Sort) Type() protoreflect.EnumType {
	return &file_category_v1_category_proto_enumTypes[2]
}

func (x GetLevelThreeRequest_Sort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetLevelThreeRequest_Sort.Descriptor instead.
func (GetLevelThreeRequest_Sort) EnumDescriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{15, 0}
}

type Category1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Category1) Reset() {
	*x = Category1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category1) ProtoMessage() {}

func (x *Category1) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category1.ProtoReflect.Descriptor instead.
func (*Category1) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{0}
}

func (x *Category1) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Category2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Category_1Id int32  `protobuf:"varint,2,opt,name=category_1_id,json=category1Id,proto3" json:"category_1_id,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Category2) Reset() {
	*x = Category2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category2) ProtoMessage() {}

func (x *Category2) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category2.ProtoReflect.Descriptor instead.
func (*Category2) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{1}
}

func (x *Category2) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category2) GetCategory_1Id() int32 {
	if x != nil {
		return x.Category_1Id
	}
	return 0
}

func (x *Category2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Category3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Category_2Id int32  `protobuf:"varint,2,opt,name=category_2_id,json=category2Id,proto3" json:"category_2_id,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Category3) Reset() {
	*x = Category3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category3) ProtoMessage() {}

func (x *Category3) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category3.ProtoReflect.Descriptor instead.
func (*Category3) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{2}
}

func (x *Category3) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category3) GetCategory_2Id() int32 {
	if x != nil {
		return x.Category_2Id
	}
	return 0
}

func (x *Category3) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAllLevelOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SortBy GetAllLevelOneRequest_Sort `protobuf:"varint,1,opt,name=sort_by,json=sortBy,proto3,enum=category.v1.GetAllLevelOneRequest_Sort" json:"sort_by,omitempty"`
}

func (x *GetAllLevelOneRequest) Reset() {
	*x = GetAllLevelOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllLevelOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLevelOneRequest) ProtoMessage() {}

func (x *GetAllLevelOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLevelOneRequest.ProtoReflect.Descriptor instead.
func (*GetAllLevelOneRequest) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllLevelOneRequest) GetSortBy() GetAllLevelOneRequest_Sort {
	if x != nil {
		return x.SortBy
	}
	return GetAllLevelOneRequest_ASCENDING_UNSPECIFIED
}

type GetAllLevelOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Category1 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllLevelOneResponse) Reset() {
	*x = GetAllLevelOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllLevelOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLevelOneResponse) ProtoMessage() {}

func (x *GetAllLevelOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLevelOneResponse.ProtoReflect.Descriptor instead.
func (*GetAllLevelOneResponse) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllLevelOneResponse) GetData() []*Category1 {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetOneLevelOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetOneLevelOneRequest) Reset() {
	*x = GetOneLevelOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneLevelOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneLevelOneRequest) ProtoMessage() {}

func (x *GetOneLevelOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneLevelOneRequest.ProtoReflect.Descriptor instead.
func (*GetOneLevelOneRequest) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{5}
}

func (x *GetOneLevelOneRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOneLevelOneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetOneLevelOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category1 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetOneLevelOneResponse) Reset() {
	*x = GetOneLevelOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneLevelOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneLevelOneResponse) ProtoMessage() {}

func (x *GetOneLevelOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneLevelOneResponse.ProtoReflect.Descriptor instead.
func (*GetOneLevelOneResponse) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{6}
}

func (x *GetOneLevelOneResponse) GetData() *Category1 {
	if x != nil {
		return x.Data
	}
	return nil
}

type InsertLevelOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *InsertLevelOneRequest) Reset() {
	*x = InsertLevelOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertLevelOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertLevelOneRequest) ProtoMessage() {}

func (x *InsertLevelOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertLevelOneRequest.ProtoReflect.Descriptor instead.
func (*InsertLevelOneRequest) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{7}
}

func (x *InsertLevelOneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InsertLevelOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category1 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *InsertLevelOneResponse) Reset() {
	*x = InsertLevelOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertLevelOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertLevelOneResponse) ProtoMessage() {}

func (x *InsertLevelOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertLevelOneResponse.ProtoReflect.Descriptor instead.
func (*InsertLevelOneResponse) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{8}
}

func (x *InsertLevelOneResponse) GetData() *Category1 {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetLevelTwoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category_1Id int32                   `protobuf:"varint,1,opt,name=category_1_id,json=category1Id,proto3" json:"category_1_id,omitempty"`
	SortBy       GetLevelTwoRequest_Sort `protobuf:"varint,2,opt,name=sort_by,json=sortBy,proto3,enum=category.v1.GetLevelTwoRequest_Sort" json:"sort_by,omitempty"`
}

func (x *GetLevelTwoRequest) Reset() {
	*x = GetLevelTwoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLevelTwoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelTwoRequest) ProtoMessage() {}

func (x *GetLevelTwoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelTwoRequest.ProtoReflect.Descriptor instead.
func (*GetLevelTwoRequest) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{9}
}

func (x *GetLevelTwoRequest) GetCategory_1Id() int32 {
	if x != nil {
		return x.Category_1Id
	}
	return 0
}

func (x *GetLevelTwoRequest) GetSortBy() GetLevelTwoRequest_Sort {
	if x != nil {
		return x.SortBy
	}
	return GetLevelTwoRequest_ASCENDING_UNSPECIFIED
}

type GetLevelTwoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Category2 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetLevelTwoResponse) Reset() {
	*x = GetLevelTwoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLevelTwoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelTwoResponse) ProtoMessage() {}

func (x *GetLevelTwoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelTwoResponse.ProtoReflect.Descriptor instead.
func (*GetLevelTwoResponse) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{10}
}

func (x *GetLevelTwoResponse) GetData() []*Category2 {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetOneLevelTwoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetOneLevelTwoRequest) Reset() {
	*x = GetOneLevelTwoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneLevelTwoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneLevelTwoRequest) ProtoMessage() {}

func (x *GetOneLevelTwoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneLevelTwoRequest.ProtoReflect.Descriptor instead.
func (*GetOneLevelTwoRequest) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{11}
}

func (x *GetOneLevelTwoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOneLevelTwoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetOneLevelTwoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category2 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetOneLevelTwoResponse) Reset() {
	*x = GetOneLevelTwoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneLevelTwoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneLevelTwoResponse) ProtoMessage() {}

func (x *GetOneLevelTwoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneLevelTwoResponse.ProtoReflect.Descriptor instead.
func (*GetOneLevelTwoResponse) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{12}
}

func (x *GetOneLevelTwoResponse) GetData() *Category2 {
	if x != nil {
		return x.Data
	}
	return nil
}

type InsertLevelTwoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category_1Id int32  `protobuf:"varint,1,opt,name=category_1_id,json=category1Id,proto3" json:"category_1_id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *InsertLevelTwoRequest) Reset() {
	*x = InsertLevelTwoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertLevelTwoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertLevelTwoRequest) ProtoMessage() {}

func (x *InsertLevelTwoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertLevelTwoRequest.ProtoReflect.Descriptor instead.
func (*InsertLevelTwoRequest) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{13}
}

func (x *InsertLevelTwoRequest) GetCategory_1Id() int32 {
	if x != nil {
		return x.Category_1Id
	}
	return 0
}

func (x *InsertLevelTwoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InsertLevelTwoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Category2 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *InsertLevelTwoResponse) Reset() {
	*x = InsertLevelTwoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertLevelTwoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertLevelTwoResponse) ProtoMessage() {}

func (x *InsertLevelTwoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertLevelTwoResponse.ProtoReflect.Descriptor instead.
func (*InsertLevelTwoResponse) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{14}
}

func (x *InsertLevelTwoResponse) GetData() []*Category2 {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetLevelThreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category_2Id int32                     `protobuf:"varint,1,opt,name=category_2_id,json=category2Id,proto3" json:"category_2_id,omitempty"`
	SortBy       GetLevelThreeRequest_Sort `protobuf:"varint,2,opt,name=sort_by,json=sortBy,proto3,enum=category.v1.GetLevelThreeRequest_Sort" json:"sort_by,omitempty"`
}

func (x *GetLevelThreeRequest) Reset() {
	*x = GetLevelThreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLevelThreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelThreeRequest) ProtoMessage() {}

func (x *GetLevelThreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelThreeRequest.ProtoReflect.Descriptor instead.
func (*GetLevelThreeRequest) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{15}
}

func (x *GetLevelThreeRequest) GetCategory_2Id() int32 {
	if x != nil {
		return x.Category_2Id
	}
	return 0
}

func (x *GetLevelThreeRequest) GetSortBy() GetLevelThreeRequest_Sort {
	if x != nil {
		return x.SortBy
	}
	return GetLevelThreeRequest_ASCENDING_UNSPECIFIED
}

type GetLevelThreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Category3 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetLevelThreeResponse) Reset() {
	*x = GetLevelThreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLevelThreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLevelThreeResponse) ProtoMessage() {}

func (x *GetLevelThreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLevelThreeResponse.ProtoReflect.Descriptor instead.
func (*GetLevelThreeResponse) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{16}
}

func (x *GetLevelThreeResponse) GetData() []*Category3 {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetOneLevelThreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetOneLevelThreeRequest) Reset() {
	*x = GetOneLevelThreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneLevelThreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneLevelThreeRequest) ProtoMessage() {}

func (x *GetOneLevelThreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneLevelThreeRequest.ProtoReflect.Descriptor instead.
func (*GetOneLevelThreeRequest) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{17}
}

func (x *GetOneLevelThreeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOneLevelThreeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetOneLevelThreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category3 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetOneLevelThreeResponse) Reset() {
	*x = GetOneLevelThreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneLevelThreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneLevelThreeResponse) ProtoMessage() {}

func (x *GetOneLevelThreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneLevelThreeResponse.ProtoReflect.Descriptor instead.
func (*GetOneLevelThreeResponse) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{18}
}

func (x *GetOneLevelThreeResponse) GetData() *Category3 {
	if x != nil {
		return x.Data
	}
	return nil
}

type InsertLevelThreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category_2Id int32  `protobuf:"varint,1,opt,name=category_2_id,json=category2Id,proto3" json:"category_2_id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *InsertLevelThreeRequest) Reset() {
	*x = InsertLevelThreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertLevelThreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertLevelThreeRequest) ProtoMessage() {}

func (x *InsertLevelThreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertLevelThreeRequest.ProtoReflect.Descriptor instead.
func (*InsertLevelThreeRequest) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{19}
}

func (x *InsertLevelThreeRequest) GetCategory_2Id() int32 {
	if x != nil {
		return x.Category_2Id
	}
	return 0
}

func (x *InsertLevelThreeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InsertLevelThreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Category3 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *InsertLevelThreeResponse) Reset() {
	*x = InsertLevelThreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_category_v1_category_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertLevelThreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertLevelThreeResponse) ProtoMessage() {}

func (x *InsertLevelThreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_v1_category_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertLevelThreeResponse.ProtoReflect.Descriptor instead.
func (*InsertLevelThreeResponse) Descriptor() ([]byte, []int) {
	return file_category_v1_category_proto_rawDescGZIP(), []int{20}
}

func (x *InsertLevelThreeResponse) GetData() []*Category3 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_category_v1_category_proto protoreflect.FileDescriptor

var file_category_v1_category_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x2f, 0x0a, 0x09, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x53, 0x0a, 0x09, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x5f, 0x31, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x53, 0x0a, 0x09, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0d,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x32, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40,
	0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x62, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x27, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79,
	0x22, 0x31, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x53, 0x43, 0x45,
	0x4e, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x45, 0x53, 0x43, 0x45, 0x4e, 0x44, 0x49, 0x4e,
	0x47, 0x10, 0x01, 0x22, 0x44, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x31, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3b, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x4f, 0x6e, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2b, 0x0a, 0x15,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x16, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0xaa, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x77, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x5f, 0x31, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x07, 0x73, 0x6f,
	0x72, 0x74, 0x5f, 0x62, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6f, 0x72,
	0x74, 0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x22, 0x31, 0x0a, 0x04, 0x53, 0x6f, 0x72,
	0x74, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x53, 0x43, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x44, 0x45, 0x53, 0x43, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x22, 0x41, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x3b, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x77,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x77, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x4f, 0x0a, 0x15, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x31, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x16, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x32, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xae, 0x01, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x32,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x32, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x62,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68,
	0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52,
	0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x22, 0x31, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12,
	0x19, 0x0a, 0x15, 0x41, 0x53, 0x43, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x45,
	0x53, 0x43, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x22, 0x43, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x3d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68,
	0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x46,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72,
	0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x51, 0x0a, 0x17, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x0d, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x32, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x32, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x46, 0x0a, 0x18, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0xc4, 0x06, 0x0a, 0x0f, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x59, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4f,
	0x6e, 0x65, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0e, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x12, 0x22, 0x2e,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x54, 0x77, 0x6f, 0x12, 0x1f, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x77, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x77, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4f,
	0x6e, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x77, 0x6f, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23,
	0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x4f, 0x6e, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x54, 0x77, 0x6f, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54,
	0x77, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x12,
	0x21, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x12, 0x24, 0x2e, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x10, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x12, 0x24, 0x2e, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x54, 0x68, 0x72, 0x65, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x56, 0x5a, 0x54, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x76, 0x70, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x6d,
	0x61, 0x74, 0x61, 0x6d, 0x61, 0x74, 0x61, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d,
	0x43, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x65, 0x75, 0x6d, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2d, 0x67, 0x6f, 0x2f, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_category_v1_category_proto_rawDescOnce sync.Once
	file_category_v1_category_proto_rawDescData = file_category_v1_category_proto_rawDesc
)

func file_category_v1_category_proto_rawDescGZIP() []byte {
	file_category_v1_category_proto_rawDescOnce.Do(func() {
		file_category_v1_category_proto_rawDescData = protoimpl.X.CompressGZIP(file_category_v1_category_proto_rawDescData)
	})
	return file_category_v1_category_proto_rawDescData
}

var file_category_v1_category_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_category_v1_category_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_category_v1_category_proto_goTypes = []interface{}{
	(GetAllLevelOneRequest_Sort)(0),  // 0: category.v1.GetAllLevelOneRequest.Sort
	(GetLevelTwoRequest_Sort)(0),     // 1: category.v1.GetLevelTwoRequest.Sort
	(GetLevelThreeRequest_Sort)(0),   // 2: category.v1.GetLevelThreeRequest.Sort
	(*Category1)(nil),                // 3: category.v1.Category1
	(*Category2)(nil),                // 4: category.v1.Category2
	(*Category3)(nil),                // 5: category.v1.Category3
	(*GetAllLevelOneRequest)(nil),    // 6: category.v1.GetAllLevelOneRequest
	(*GetAllLevelOneResponse)(nil),   // 7: category.v1.GetAllLevelOneResponse
	(*GetOneLevelOneRequest)(nil),    // 8: category.v1.GetOneLevelOneRequest
	(*GetOneLevelOneResponse)(nil),   // 9: category.v1.GetOneLevelOneResponse
	(*InsertLevelOneRequest)(nil),    // 10: category.v1.InsertLevelOneRequest
	(*InsertLevelOneResponse)(nil),   // 11: category.v1.InsertLevelOneResponse
	(*GetLevelTwoRequest)(nil),       // 12: category.v1.GetLevelTwoRequest
	(*GetLevelTwoResponse)(nil),      // 13: category.v1.GetLevelTwoResponse
	(*GetOneLevelTwoRequest)(nil),    // 14: category.v1.GetOneLevelTwoRequest
	(*GetOneLevelTwoResponse)(nil),   // 15: category.v1.GetOneLevelTwoResponse
	(*InsertLevelTwoRequest)(nil),    // 16: category.v1.InsertLevelTwoRequest
	(*InsertLevelTwoResponse)(nil),   // 17: category.v1.InsertLevelTwoResponse
	(*GetLevelThreeRequest)(nil),     // 18: category.v1.GetLevelThreeRequest
	(*GetLevelThreeResponse)(nil),    // 19: category.v1.GetLevelThreeResponse
	(*GetOneLevelThreeRequest)(nil),  // 20: category.v1.GetOneLevelThreeRequest
	(*GetOneLevelThreeResponse)(nil), // 21: category.v1.GetOneLevelThreeResponse
	(*InsertLevelThreeRequest)(nil),  // 22: category.v1.InsertLevelThreeRequest
	(*InsertLevelThreeResponse)(nil), // 23: category.v1.InsertLevelThreeResponse
}
var file_category_v1_category_proto_depIdxs = []int32{
	0,  // 0: category.v1.GetAllLevelOneRequest.sort_by:type_name -> category.v1.GetAllLevelOneRequest.Sort
	3,  // 1: category.v1.GetAllLevelOneResponse.data:type_name -> category.v1.Category1
	3,  // 2: category.v1.GetOneLevelOneResponse.data:type_name -> category.v1.Category1
	3,  // 3: category.v1.InsertLevelOneResponse.data:type_name -> category.v1.Category1
	1,  // 4: category.v1.GetLevelTwoRequest.sort_by:type_name -> category.v1.GetLevelTwoRequest.Sort
	4,  // 5: category.v1.GetLevelTwoResponse.data:type_name -> category.v1.Category2
	4,  // 6: category.v1.GetOneLevelTwoResponse.data:type_name -> category.v1.Category2
	4,  // 7: category.v1.InsertLevelTwoResponse.data:type_name -> category.v1.Category2
	2,  // 8: category.v1.GetLevelThreeRequest.sort_by:type_name -> category.v1.GetLevelThreeRequest.Sort
	5,  // 9: category.v1.GetLevelThreeResponse.data:type_name -> category.v1.Category3
	5,  // 10: category.v1.GetOneLevelThreeResponse.data:type_name -> category.v1.Category3
	5,  // 11: category.v1.InsertLevelThreeResponse.data:type_name -> category.v1.Category3
	6,  // 12: category.v1.CategoryService.GetAllLevelOne:input_type -> category.v1.GetAllLevelOneRequest
	8,  // 13: category.v1.CategoryService.GetOneLevelOne:input_type -> category.v1.GetOneLevelOneRequest
	10, // 14: category.v1.CategoryService.InsertLevelOne:input_type -> category.v1.InsertLevelOneRequest
	12, // 15: category.v1.CategoryService.GetLevelTwo:input_type -> category.v1.GetLevelTwoRequest
	14, // 16: category.v1.CategoryService.GetOneLevelTwo:input_type -> category.v1.GetOneLevelTwoRequest
	16, // 17: category.v1.CategoryService.InsertLevelTwo:input_type -> category.v1.InsertLevelTwoRequest
	18, // 18: category.v1.CategoryService.GetLevelThree:input_type -> category.v1.GetLevelThreeRequest
	20, // 19: category.v1.CategoryService.GetOneLevelThree:input_type -> category.v1.GetOneLevelThreeRequest
	22, // 20: category.v1.CategoryService.InsertLevelThree:input_type -> category.v1.InsertLevelThreeRequest
	7,  // 21: category.v1.CategoryService.GetAllLevelOne:output_type -> category.v1.GetAllLevelOneResponse
	9,  // 22: category.v1.CategoryService.GetOneLevelOne:output_type -> category.v1.GetOneLevelOneResponse
	11, // 23: category.v1.CategoryService.InsertLevelOne:output_type -> category.v1.InsertLevelOneResponse
	13, // 24: category.v1.CategoryService.GetLevelTwo:output_type -> category.v1.GetLevelTwoResponse
	15, // 25: category.v1.CategoryService.GetOneLevelTwo:output_type -> category.v1.GetOneLevelTwoResponse
	17, // 26: category.v1.CategoryService.InsertLevelTwo:output_type -> category.v1.InsertLevelTwoResponse
	19, // 27: category.v1.CategoryService.GetLevelThree:output_type -> category.v1.GetLevelThreeResponse
	21, // 28: category.v1.CategoryService.GetOneLevelThree:output_type -> category.v1.GetOneLevelThreeResponse
	23, // 29: category.v1.CategoryService.InsertLevelThree:output_type -> category.v1.InsertLevelThreeResponse
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_category_v1_category_proto_init() }
func file_category_v1_category_proto_init() {
	if File_category_v1_category_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_category_v1_category_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllLevelOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllLevelOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneLevelOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneLevelOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertLevelOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertLevelOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLevelTwoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLevelTwoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneLevelTwoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneLevelTwoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertLevelTwoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertLevelTwoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLevelThreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLevelThreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneLevelThreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneLevelThreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertLevelThreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_category_v1_category_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertLevelThreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_category_v1_category_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_v1_category_proto_goTypes,
		DependencyIndexes: file_category_v1_category_proto_depIdxs,
		EnumInfos:         file_category_v1_category_proto_enumTypes,
		MessageInfos:      file_category_v1_category_proto_msgTypes,
	}.Build()
	File_category_v1_category_proto = out.File
	file_category_v1_category_proto_rawDesc = nil
	file_category_v1_category_proto_goTypes = nil
	file_category_v1_category_proto_depIdxs = nil
}
