// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.2
// source: contents/v1/category.proto

package contents_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Category1) Reset() {
	*x = Category1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category1) ProtoMessage() {}

func (x *Category1) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category1.ProtoReflect.Descriptor instead.
func (*Category1) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{0}
}

func (x *Category1) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Category1CreateUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Category1CreateUpdate) Reset() {
	*x = Category1CreateUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category1CreateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category1CreateUpdate) ProtoMessage() {}

func (x *Category1CreateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category1CreateUpdate.ProtoReflect.Descriptor instead.
func (*Category1CreateUpdate) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{1}
}

func (x *Category1CreateUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Category2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Category1Id int32  `protobuf:"varint,2,opt,name=category1_id,json=category1Id,proto3" json:"category1_id,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Category2) Reset() {
	*x = Category2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category2) ProtoMessage() {}

func (x *Category2) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category2.ProtoReflect.Descriptor instead.
func (*Category2) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{2}
}

func (x *Category2) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category2) GetCategory1Id() int32 {
	if x != nil {
		return x.Category1Id
	}
	return 0
}

func (x *Category2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Category2CreateUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category1Id int32  `protobuf:"varint,1,opt,name=category1_id,json=category1Id,proto3" json:"category1_id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Category2CreateUpdate) Reset() {
	*x = Category2CreateUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category2CreateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category2CreateUpdate) ProtoMessage() {}

func (x *Category2CreateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category2CreateUpdate.ProtoReflect.Descriptor instead.
func (*Category2CreateUpdate) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{3}
}

func (x *Category2CreateUpdate) GetCategory1Id() int32 {
	if x != nil {
		return x.Category1Id
	}
	return 0
}

func (x *Category2CreateUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Category3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Category2Id int32  `protobuf:"varint,2,opt,name=category2_id,json=category2Id,proto3" json:"category2_id,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Category3) Reset() {
	*x = Category3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category3) ProtoMessage() {}

func (x *Category3) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category3.ProtoReflect.Descriptor instead.
func (*Category3) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{4}
}

func (x *Category3) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category3) GetCategory2Id() int32 {
	if x != nil {
		return x.Category2Id
	}
	return 0
}

func (x *Category3) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Category3CreateUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category2Id int32  `protobuf:"varint,1,opt,name=category2_id,json=category2Id,proto3" json:"category2_id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Category3CreateUpdate) Reset() {
	*x = Category3CreateUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category3CreateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category3CreateUpdate) ProtoMessage() {}

func (x *Category3CreateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category3CreateUpdate.ProtoReflect.Descriptor instead.
func (*Category3CreateUpdate) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{5}
}

func (x *Category3CreateUpdate) GetCategory2Id() int32 {
	if x != nil {
		return x.Category2Id
	}
	return 0
}

func (x *Category3CreateUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Category1GetOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Category1GetOneRequest) Reset() {
	*x = Category1GetOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category1GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category1GetOneRequest) ProtoMessage() {}

func (x *Category1GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category1GetOneRequest.ProtoReflect.Descriptor instead.
func (*Category1GetOneRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{6}
}

func (x *Category1GetOneRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Category1GetOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category1 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category1GetOneResponse) Reset() {
	*x = Category1GetOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category1GetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category1GetOneResponse) ProtoMessage() {}

func (x *Category1GetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category1GetOneResponse.ProtoReflect.Descriptor instead.
func (*Category1GetOneResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{7}
}

func (x *Category1GetOneResponse) GetData() *Category1 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category2GetOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Category2GetOneRequest) Reset() {
	*x = Category2GetOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category2GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category2GetOneRequest) ProtoMessage() {}

func (x *Category2GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category2GetOneRequest.ProtoReflect.Descriptor instead.
func (*Category2GetOneRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{8}
}

func (x *Category2GetOneRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Category2GetOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category2 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category2GetOneResponse) Reset() {
	*x = Category2GetOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category2GetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category2GetOneResponse) ProtoMessage() {}

func (x *Category2GetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category2GetOneResponse.ProtoReflect.Descriptor instead.
func (*Category2GetOneResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{9}
}

func (x *Category2GetOneResponse) GetData() *Category2 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category3GetOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Category3GetOneRequest) Reset() {
	*x = Category3GetOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category3GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category3GetOneRequest) ProtoMessage() {}

func (x *Category3GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category3GetOneRequest.ProtoReflect.Descriptor instead.
func (*Category3GetOneRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{10}
}

func (x *Category3GetOneRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Category3GetOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category3 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category3GetOneResponse) Reset() {
	*x = Category3GetOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category3GetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category3GetOneResponse) ProtoMessage() {}

func (x *Category3GetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category3GetOneResponse.ProtoReflect.Descriptor instead.
func (*Category3GetOneResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{11}
}

func (x *Category3GetOneResponse) GetData() *Category3 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category1GetMultipleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Category1GetMultipleRequest) Reset() {
	*x = Category1GetMultipleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category1GetMultipleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category1GetMultipleRequest) ProtoMessage() {}

func (x *Category1GetMultipleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category1GetMultipleRequest.ProtoReflect.Descriptor instead.
func (*Category1GetMultipleRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{12}
}

type Category1GetMultipleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Category1 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *Category1GetMultipleResponse) Reset() {
	*x = Category1GetMultipleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category1GetMultipleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category1GetMultipleResponse) ProtoMessage() {}

func (x *Category1GetMultipleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category1GetMultipleResponse.ProtoReflect.Descriptor instead.
func (*Category1GetMultipleResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{13}
}

func (x *Category1GetMultipleResponse) GetData() []*Category1 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category2GetMultipleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category1Id int32 `protobuf:"varint,1,opt,name=category1_id,json=category1Id,proto3" json:"category1_id,omitempty"`
}

func (x *Category2GetMultipleRequest) Reset() {
	*x = Category2GetMultipleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category2GetMultipleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category2GetMultipleRequest) ProtoMessage() {}

func (x *Category2GetMultipleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category2GetMultipleRequest.ProtoReflect.Descriptor instead.
func (*Category2GetMultipleRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{14}
}

func (x *Category2GetMultipleRequest) GetCategory1Id() int32 {
	if x != nil {
		return x.Category1Id
	}
	return 0
}

type Category2GetMultipleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Category2 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *Category2GetMultipleResponse) Reset() {
	*x = Category2GetMultipleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category2GetMultipleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category2GetMultipleResponse) ProtoMessage() {}

func (x *Category2GetMultipleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category2GetMultipleResponse.ProtoReflect.Descriptor instead.
func (*Category2GetMultipleResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{15}
}

func (x *Category2GetMultipleResponse) GetData() []*Category2 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category3GetMultipleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category2Id int32 `protobuf:"varint,1,opt,name=category2_id,json=category2Id,proto3" json:"category2_id,omitempty"`
}

func (x *Category3GetMultipleRequest) Reset() {
	*x = Category3GetMultipleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category3GetMultipleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category3GetMultipleRequest) ProtoMessage() {}

func (x *Category3GetMultipleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category3GetMultipleRequest.ProtoReflect.Descriptor instead.
func (*Category3GetMultipleRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{16}
}

func (x *Category3GetMultipleRequest) GetCategory2Id() int32 {
	if x != nil {
		return x.Category2Id
	}
	return 0
}

type Category3GetMultipleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Category3 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *Category3GetMultipleResponse) Reset() {
	*x = Category3GetMultipleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category3GetMultipleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category3GetMultipleResponse) ProtoMessage() {}

func (x *Category3GetMultipleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category3GetMultipleResponse.ProtoReflect.Descriptor instead.
func (*Category3GetMultipleResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{17}
}

func (x *Category3GetMultipleResponse) GetData() []*Category3 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category1CreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category1CreateUpdate `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category1CreateRequest) Reset() {
	*x = Category1CreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category1CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category1CreateRequest) ProtoMessage() {}

func (x *Category1CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category1CreateRequest.ProtoReflect.Descriptor instead.
func (*Category1CreateRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{18}
}

func (x *Category1CreateRequest) GetData() *Category1CreateUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category1CreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category1 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category1CreateResponse) Reset() {
	*x = Category1CreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category1CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category1CreateResponse) ProtoMessage() {}

func (x *Category1CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category1CreateResponse.ProtoReflect.Descriptor instead.
func (*Category1CreateResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{19}
}

func (x *Category1CreateResponse) GetData() *Category1 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category2CreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category2CreateUpdate `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category2CreateRequest) Reset() {
	*x = Category2CreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category2CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category2CreateRequest) ProtoMessage() {}

func (x *Category2CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category2CreateRequest.ProtoReflect.Descriptor instead.
func (*Category2CreateRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{20}
}

func (x *Category2CreateRequest) GetData() *Category2CreateUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category2CreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category2 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category2CreateResponse) Reset() {
	*x = Category2CreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category2CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category2CreateResponse) ProtoMessage() {}

func (x *Category2CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category2CreateResponse.ProtoReflect.Descriptor instead.
func (*Category2CreateResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{21}
}

func (x *Category2CreateResponse) GetData() *Category2 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category3CreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category3CreateUpdate `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category3CreateRequest) Reset() {
	*x = Category3CreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category3CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category3CreateRequest) ProtoMessage() {}

func (x *Category3CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category3CreateRequest.ProtoReflect.Descriptor instead.
func (*Category3CreateRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{22}
}

func (x *Category3CreateRequest) GetData() *Category3CreateUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category3CreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category3 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category3CreateResponse) Reset() {
	*x = Category3CreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category3CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category3CreateResponse) ProtoMessage() {}

func (x *Category3CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category3CreateResponse.ProtoReflect.Descriptor instead.
func (*Category3CreateResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{23}
}

func (x *Category3CreateResponse) GetData() *Category3 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category1UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data *Category1CreateUpdate `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category1UpdateRequest) Reset() {
	*x = Category1UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category1UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category1UpdateRequest) ProtoMessage() {}

func (x *Category1UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category1UpdateRequest.ProtoReflect.Descriptor instead.
func (*Category1UpdateRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{24}
}

func (x *Category1UpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category1UpdateRequest) GetData() *Category1CreateUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category1UpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category1 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category1UpdateResponse) Reset() {
	*x = Category1UpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category1UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category1UpdateResponse) ProtoMessage() {}

func (x *Category1UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category1UpdateResponse.ProtoReflect.Descriptor instead.
func (*Category1UpdateResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{25}
}

func (x *Category1UpdateResponse) GetData() *Category1 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category2UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data *Category2CreateUpdate `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category2UpdateRequest) Reset() {
	*x = Category2UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category2UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category2UpdateRequest) ProtoMessage() {}

func (x *Category2UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category2UpdateRequest.ProtoReflect.Descriptor instead.
func (*Category2UpdateRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{26}
}

func (x *Category2UpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category2UpdateRequest) GetData() *Category2CreateUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category2UpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category2 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category2UpdateResponse) Reset() {
	*x = Category2UpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category2UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category2UpdateResponse) ProtoMessage() {}

func (x *Category2UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category2UpdateResponse.ProtoReflect.Descriptor instead.
func (*Category2UpdateResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{27}
}

func (x *Category2UpdateResponse) GetData() *Category2 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category3UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data *Category3CreateUpdate `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category3UpdateRequest) Reset() {
	*x = Category3UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category3UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category3UpdateRequest) ProtoMessage() {}

func (x *Category3UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category3UpdateRequest.ProtoReflect.Descriptor instead.
func (*Category3UpdateRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{28}
}

func (x *Category3UpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category3UpdateRequest) GetData() *Category3CreateUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category3UpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Category3 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Category3UpdateResponse) Reset() {
	*x = Category3UpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category3UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category3UpdateResponse) ProtoMessage() {}

func (x *Category3UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category3UpdateResponse.ProtoReflect.Descriptor instead.
func (*Category3UpdateResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{29}
}

func (x *Category3UpdateResponse) GetData() *Category3 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Category1DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Category1DeleteRequest) Reset() {
	*x = Category1DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category1DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category1DeleteRequest) ProtoMessage() {}

func (x *Category1DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category1DeleteRequest.ProtoReflect.Descriptor instead.
func (*Category1DeleteRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{30}
}

func (x *Category1DeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Category1DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Category1DeleteResponse) Reset() {
	*x = Category1DeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category1DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category1DeleteResponse) ProtoMessage() {}

func (x *Category1DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category1DeleteResponse.ProtoReflect.Descriptor instead.
func (*Category1DeleteResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{31}
}

type Category2DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Category2DeleteRequest) Reset() {
	*x = Category2DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category2DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category2DeleteRequest) ProtoMessage() {}

func (x *Category2DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category2DeleteRequest.ProtoReflect.Descriptor instead.
func (*Category2DeleteRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{32}
}

func (x *Category2DeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Category2DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Category2DeleteResponse) Reset() {
	*x = Category2DeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category2DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category2DeleteResponse) ProtoMessage() {}

func (x *Category2DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category2DeleteResponse.ProtoReflect.Descriptor instead.
func (*Category2DeleteResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{33}
}

type Category3DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Category3DeleteRequest) Reset() {
	*x = Category3DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category3DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category3DeleteRequest) ProtoMessage() {}

func (x *Category3DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category3DeleteRequest.ProtoReflect.Descriptor instead.
func (*Category3DeleteRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{34}
}

func (x *Category3DeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Category3DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Category3DeleteResponse) Reset() {
	*x = Category3DeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_category_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category3DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category3DeleteResponse) ProtoMessage() {}

func (x *Category3DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_category_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category3DeleteResponse.ProtoReflect.Descriptor instead.
func (*Category3DeleteResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_category_proto_rawDescGZIP(), []int{35}
}

var File_contents_v1_category_proto protoreflect.FileDescriptor

var file_contents_v1_category_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x2f, 0x0a, 0x09, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x15, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x52, 0x0a, 0x09, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x31, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x31, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4e, 0x0a, 0x15, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x31, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x31, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x52, 0x0a, 0x09, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x32, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x4e, 0x0a, 0x15, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x32, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x28, 0x0a, 0x16, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x47, 0x65, 0x74, 0x4f,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x17, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x28, 0x0a, 0x16, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x47, 0x65, 0x74,
	0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x17, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x28, 0x0a, 0x16, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x47, 0x65,
	0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x17, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x47,
	0x65, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x4a, 0x0a, 0x1c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x47, 0x65,
	0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x40, 0x0a,
	0x1b, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x49, 0x64, 0x22,
	0x4a, 0x0a, 0x1c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x47, 0x65, 0x74, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x32, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x40, 0x0a, 0x1b, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x49, 0x64, 0x22, 0x4a, 0x0a,
	0x1c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x33, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x16, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x17, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x50, 0x0a, 0x16, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x32, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x17, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x32, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x32, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x16, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x45, 0x0a,
	0x17, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x60, 0x0a, 0x16, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x31, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x31, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x17, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x31, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x60, 0x0a,
	0x16, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x45, 0x0a, 0x17, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x60, 0x0a, 0x16, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x33, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x17, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x33, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x28, 0x0a, 0x16, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28, 0x0a, 0x16, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x32, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19,
	0x0a, 0x17, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x32, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28, 0x0a, 0x16, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x33, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x33,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x49,
	0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x76, 0x70,
	0x2d, 0x64, 0x65, 0x76, 0x2f, 0x6d, 0x61, 0x74, 0x61, 0x6d, 0x61, 0x74, 0x61, 0x2d, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2d, 0x67, 0x6f, 0x2f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_contents_v1_category_proto_rawDescOnce sync.Once
	file_contents_v1_category_proto_rawDescData = file_contents_v1_category_proto_rawDesc
)

func file_contents_v1_category_proto_rawDescGZIP() []byte {
	file_contents_v1_category_proto_rawDescOnce.Do(func() {
		file_contents_v1_category_proto_rawDescData = protoimpl.X.CompressGZIP(file_contents_v1_category_proto_rawDescData)
	})
	return file_contents_v1_category_proto_rawDescData
}

var file_contents_v1_category_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_contents_v1_category_proto_goTypes = []interface{}{
	(*Category1)(nil),                    // 0: contents.v1.Category1
	(*Category1CreateUpdate)(nil),        // 1: contents.v1.Category1CreateUpdate
	(*Category2)(nil),                    // 2: contents.v1.Category2
	(*Category2CreateUpdate)(nil),        // 3: contents.v1.Category2CreateUpdate
	(*Category3)(nil),                    // 4: contents.v1.Category3
	(*Category3CreateUpdate)(nil),        // 5: contents.v1.Category3CreateUpdate
	(*Category1GetOneRequest)(nil),       // 6: contents.v1.Category1GetOneRequest
	(*Category1GetOneResponse)(nil),      // 7: contents.v1.Category1GetOneResponse
	(*Category2GetOneRequest)(nil),       // 8: contents.v1.Category2GetOneRequest
	(*Category2GetOneResponse)(nil),      // 9: contents.v1.Category2GetOneResponse
	(*Category3GetOneRequest)(nil),       // 10: contents.v1.Category3GetOneRequest
	(*Category3GetOneResponse)(nil),      // 11: contents.v1.Category3GetOneResponse
	(*Category1GetMultipleRequest)(nil),  // 12: contents.v1.Category1GetMultipleRequest
	(*Category1GetMultipleResponse)(nil), // 13: contents.v1.Category1GetMultipleResponse
	(*Category2GetMultipleRequest)(nil),  // 14: contents.v1.Category2GetMultipleRequest
	(*Category2GetMultipleResponse)(nil), // 15: contents.v1.Category2GetMultipleResponse
	(*Category3GetMultipleRequest)(nil),  // 16: contents.v1.Category3GetMultipleRequest
	(*Category3GetMultipleResponse)(nil), // 17: contents.v1.Category3GetMultipleResponse
	(*Category1CreateRequest)(nil),       // 18: contents.v1.Category1CreateRequest
	(*Category1CreateResponse)(nil),      // 19: contents.v1.Category1CreateResponse
	(*Category2CreateRequest)(nil),       // 20: contents.v1.Category2CreateRequest
	(*Category2CreateResponse)(nil),      // 21: contents.v1.Category2CreateResponse
	(*Category3CreateRequest)(nil),       // 22: contents.v1.Category3CreateRequest
	(*Category3CreateResponse)(nil),      // 23: contents.v1.Category3CreateResponse
	(*Category1UpdateRequest)(nil),       // 24: contents.v1.Category1UpdateRequest
	(*Category1UpdateResponse)(nil),      // 25: contents.v1.Category1UpdateResponse
	(*Category2UpdateRequest)(nil),       // 26: contents.v1.Category2UpdateRequest
	(*Category2UpdateResponse)(nil),      // 27: contents.v1.Category2UpdateResponse
	(*Category3UpdateRequest)(nil),       // 28: contents.v1.Category3UpdateRequest
	(*Category3UpdateResponse)(nil),      // 29: contents.v1.Category3UpdateResponse
	(*Category1DeleteRequest)(nil),       // 30: contents.v1.Category1DeleteRequest
	(*Category1DeleteResponse)(nil),      // 31: contents.v1.Category1DeleteResponse
	(*Category2DeleteRequest)(nil),       // 32: contents.v1.Category2DeleteRequest
	(*Category2DeleteResponse)(nil),      // 33: contents.v1.Category2DeleteResponse
	(*Category3DeleteRequest)(nil),       // 34: contents.v1.Category3DeleteRequest
	(*Category3DeleteResponse)(nil),      // 35: contents.v1.Category3DeleteResponse
}
var file_contents_v1_category_proto_depIdxs = []int32{
	0,  // 0: contents.v1.Category1GetOneResponse.data:type_name -> contents.v1.Category1
	2,  // 1: contents.v1.Category2GetOneResponse.data:type_name -> contents.v1.Category2
	4,  // 2: contents.v1.Category3GetOneResponse.data:type_name -> contents.v1.Category3
	0,  // 3: contents.v1.Category1GetMultipleResponse.data:type_name -> contents.v1.Category1
	2,  // 4: contents.v1.Category2GetMultipleResponse.data:type_name -> contents.v1.Category2
	4,  // 5: contents.v1.Category3GetMultipleResponse.data:type_name -> contents.v1.Category3
	1,  // 6: contents.v1.Category1CreateRequest.data:type_name -> contents.v1.Category1CreateUpdate
	0,  // 7: contents.v1.Category1CreateResponse.data:type_name -> contents.v1.Category1
	3,  // 8: contents.v1.Category2CreateRequest.data:type_name -> contents.v1.Category2CreateUpdate
	2,  // 9: contents.v1.Category2CreateResponse.data:type_name -> contents.v1.Category2
	5,  // 10: contents.v1.Category3CreateRequest.data:type_name -> contents.v1.Category3CreateUpdate
	4,  // 11: contents.v1.Category3CreateResponse.data:type_name -> contents.v1.Category3
	1,  // 12: contents.v1.Category1UpdateRequest.data:type_name -> contents.v1.Category1CreateUpdate
	0,  // 13: contents.v1.Category1UpdateResponse.data:type_name -> contents.v1.Category1
	3,  // 14: contents.v1.Category2UpdateRequest.data:type_name -> contents.v1.Category2CreateUpdate
	2,  // 15: contents.v1.Category2UpdateResponse.data:type_name -> contents.v1.Category2
	5,  // 16: contents.v1.Category3UpdateRequest.data:type_name -> contents.v1.Category3CreateUpdate
	4,  // 17: contents.v1.Category3UpdateResponse.data:type_name -> contents.v1.Category3
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_contents_v1_category_proto_init() }
func file_contents_v1_category_proto_init() {
	if File_contents_v1_category_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contents_v1_category_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category1CreateUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category2CreateUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category3CreateUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category1GetOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category1GetOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category2GetOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category2GetOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category3GetOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category3GetOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category1GetMultipleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category1GetMultipleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category2GetMultipleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category2GetMultipleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category3GetMultipleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category3GetMultipleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category1CreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category1CreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category2CreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category2CreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category3CreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category3CreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category1UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category1UpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category2UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category2UpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category3UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category3UpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category1DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category1DeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category2DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category2DeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category3DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_category_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category3DeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contents_v1_category_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contents_v1_category_proto_goTypes,
		DependencyIndexes: file_contents_v1_category_proto_depIdxs,
		MessageInfos:      file_contents_v1_category_proto_msgTypes,
	}.Build()
	File_contents_v1_category_proto = out.File
	file_contents_v1_category_proto_rawDesc = nil
	file_contents_v1_category_proto_goTypes = nil
	file_contents_v1_category_proto_depIdxs = nil
}
