// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        v3.15.2
// source: contents/v1/tag.proto

package contents_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// sorting
type TagGetMultipleRequest_SortDirection int32

const (
	TagGetMultipleRequest_A_TO_Z_UNSPECIFIED TagGetMultipleRequest_SortDirection = 0
	TagGetMultipleRequest_Z_TO_A             TagGetMultipleRequest_SortDirection = 1
)

// Enum value maps for TagGetMultipleRequest_SortDirection.
var (
	TagGetMultipleRequest_SortDirection_name = map[int32]string{
		0: "A_TO_Z_UNSPECIFIED",
		1: "Z_TO_A",
	}
	TagGetMultipleRequest_SortDirection_value = map[string]int32{
		"A_TO_Z_UNSPECIFIED": 0,
		"Z_TO_A":             1,
	}
)

func (x TagGetMultipleRequest_SortDirection) Enum() *TagGetMultipleRequest_SortDirection {
	p := new(TagGetMultipleRequest_SortDirection)
	*p = x
	return p
}

func (x TagGetMultipleRequest_SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagGetMultipleRequest_SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_contents_v1_tag_proto_enumTypes[0].Descriptor()
}

func (TagGetMultipleRequest_SortDirection) Type() protoreflect.EnumType {
	return &file_contents_v1_tag_proto_enumTypes[0]
}

func (x TagGetMultipleRequest_SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagGetMultipleRequest_SortDirection.Descriptor instead.
func (TagGetMultipleRequest_SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_contents_v1_tag_proto_rawDescGZIP(), []int{4, 0}
}

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_tag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_tag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_contents_v1_tag_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TagCreateUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TagCreateUpdate) Reset() {
	*x = TagCreateUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_tag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagCreateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagCreateUpdate) ProtoMessage() {}

func (x *TagCreateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_tag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagCreateUpdate.ProtoReflect.Descriptor instead.
func (*TagCreateUpdate) Descriptor() ([]byte, []int) {
	return file_contents_v1_tag_proto_rawDescGZIP(), []int{1}
}

func (x *TagCreateUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TagGetOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SearchByName string `protobuf:"bytes,2,opt,name=search_by_name,json=searchByName,proto3" json:"search_by_name,omitempty"`
}

func (x *TagGetOneRequest) Reset() {
	*x = TagGetOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_tag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagGetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagGetOneRequest) ProtoMessage() {}

func (x *TagGetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_tag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagGetOneRequest.ProtoReflect.Descriptor instead.
func (*TagGetOneRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_tag_proto_rawDescGZIP(), []int{2}
}

func (x *TagGetOneRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagGetOneRequest) GetSearchByName() string {
	if x != nil {
		return x.SearchByName
	}
	return ""
}

type TagGetOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Tag `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TagGetOneResponse) Reset() {
	*x = TagGetOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_tag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagGetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagGetOneResponse) ProtoMessage() {}

func (x *TagGetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_tag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagGetOneResponse.ProtoReflect.Descriptor instead.
func (*TagGetOneResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_tag_proto_rawDescGZIP(), []int{3}
}

func (x *TagGetOneResponse) GetData() *Tag {
	if x != nil {
		return x.Data
	}
	return nil
}

type TagGetMultipleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// filtering
	SearchByName string                              `protobuf:"bytes,1,opt,name=search_by_name,json=searchByName,proto3" json:"search_by_name,omitempty"`
	Ids          []int32                             `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	SortBy       TagGetMultipleRequest_SortDirection `protobuf:"varint,11,opt,name=sort_by,json=sortBy,proto3,enum=contents.v1.TagGetMultipleRequest_SortDirection" json:"sort_by,omitempty"`
}

func (x *TagGetMultipleRequest) Reset() {
	*x = TagGetMultipleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_tag_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagGetMultipleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagGetMultipleRequest) ProtoMessage() {}

func (x *TagGetMultipleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_tag_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagGetMultipleRequest.ProtoReflect.Descriptor instead.
func (*TagGetMultipleRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_tag_proto_rawDescGZIP(), []int{4}
}

func (x *TagGetMultipleRequest) GetSearchByName() string {
	if x != nil {
		return x.SearchByName
	}
	return ""
}

func (x *TagGetMultipleRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *TagGetMultipleRequest) GetSortBy() TagGetMultipleRequest_SortDirection {
	if x != nil {
		return x.SortBy
	}
	return TagGetMultipleRequest_A_TO_Z_UNSPECIFIED
}

type TagGetMultipleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Tag `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *TagGetMultipleResponse) Reset() {
	*x = TagGetMultipleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_tag_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagGetMultipleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagGetMultipleResponse) ProtoMessage() {}

func (x *TagGetMultipleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_tag_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagGetMultipleResponse.ProtoReflect.Descriptor instead.
func (*TagGetMultipleResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_tag_proto_rawDescGZIP(), []int{5}
}

func (x *TagGetMultipleResponse) GetData() []*Tag {
	if x != nil {
		return x.Data
	}
	return nil
}

type TagCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *TagCreateUpdate `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TagCreateRequest) Reset() {
	*x = TagCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_tag_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagCreateRequest) ProtoMessage() {}

func (x *TagCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_tag_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagCreateRequest.ProtoReflect.Descriptor instead.
func (*TagCreateRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_tag_proto_rawDescGZIP(), []int{6}
}

func (x *TagCreateRequest) GetData() *TagCreateUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

type TagCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Tag `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TagCreateResponse) Reset() {
	*x = TagCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_tag_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagCreateResponse) ProtoMessage() {}

func (x *TagCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_tag_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagCreateResponse.ProtoReflect.Descriptor instead.
func (*TagCreateResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_tag_proto_rawDescGZIP(), []int{7}
}

func (x *TagCreateResponse) GetData() *Tag {
	if x != nil {
		return x.Data
	}
	return nil
}

type TagUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data *TagCreateUpdate `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TagUpdateRequest) Reset() {
	*x = TagUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_tag_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagUpdateRequest) ProtoMessage() {}

func (x *TagUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_tag_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagUpdateRequest.ProtoReflect.Descriptor instead.
func (*TagUpdateRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_tag_proto_rawDescGZIP(), []int{8}
}

func (x *TagUpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagUpdateRequest) GetData() *TagCreateUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

type TagUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Tag `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TagUpdateResponse) Reset() {
	*x = TagUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_tag_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagUpdateResponse) ProtoMessage() {}

func (x *TagUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_tag_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagUpdateResponse.ProtoReflect.Descriptor instead.
func (*TagUpdateResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_tag_proto_rawDescGZIP(), []int{9}
}

func (x *TagUpdateResponse) GetData() *Tag {
	if x != nil {
		return x.Data
	}
	return nil
}

type TagDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids  []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Name string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TagDeleteRequest) Reset() {
	*x = TagDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_tag_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagDeleteRequest) ProtoMessage() {}

func (x *TagDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_tag_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagDeleteRequest.ProtoReflect.Descriptor instead.
func (*TagDeleteRequest) Descriptor() ([]byte, []int) {
	return file_contents_v1_tag_proto_rawDescGZIP(), []int{10}
}

func (x *TagDeleteRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *TagDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TagDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TagDeleteResponse) Reset() {
	*x = TagDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contents_v1_tag_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagDeleteResponse) ProtoMessage() {}

func (x *TagDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contents_v1_tag_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagDeleteResponse.ProtoReflect.Descriptor instead.
func (*TagDeleteResponse) Descriptor() ([]byte, []int) {
	return file_contents_v1_tag_proto_rawDescGZIP(), []int{11}
}

var File_contents_v1_tag_proto protoreflect.FileDescriptor

var file_contents_v1_tag_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x61,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x22, 0x29, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x25, 0x0a, 0x0f, 0x54, 0x61, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x10, 0x54, 0x61, 0x67, 0x47, 0x65, 0x74,
	0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x39, 0x0a, 0x11, 0x54, 0x61, 0x67, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xcf, 0x01, 0x0a, 0x15,
	0x54, 0x61, 0x67, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f,
	0x62, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x49, 0x0a,
	0x07, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x62, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x30,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x67,
	0x47, 0x65, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x22, 0x33, 0x0a, 0x0d, 0x53, 0x6f, 0x72, 0x74,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x5f, 0x54,
	0x4f, 0x5f, 0x5a, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x5a, 0x5f, 0x54, 0x4f, 0x5f, 0x41, 0x10, 0x01, 0x22, 0x3e, 0x0a,
	0x16, 0x54, 0x61, 0x67, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x44, 0x0a,
	0x10, 0x54, 0x61, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61,
	0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x39, 0x0a, 0x11, 0x54, 0x61, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x54,
	0x0a, 0x10, 0x54, 0x61, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x61, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x39, 0x0a, 0x11, 0x54, 0x61, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x38, 0x0a, 0x10, 0x54, 0x61, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x54, 0x61, 0x67,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x49,
	0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x76, 0x70,
	0x2d, 0x64, 0x65, 0x76, 0x2f, 0x6d, 0x61, 0x74, 0x61, 0x6d, 0x61, 0x74, 0x61, 0x2d, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2d, 0x67, 0x6f, 0x2f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_contents_v1_tag_proto_rawDescOnce sync.Once
	file_contents_v1_tag_proto_rawDescData = file_contents_v1_tag_proto_rawDesc
)

func file_contents_v1_tag_proto_rawDescGZIP() []byte {
	file_contents_v1_tag_proto_rawDescOnce.Do(func() {
		file_contents_v1_tag_proto_rawDescData = protoimpl.X.CompressGZIP(file_contents_v1_tag_proto_rawDescData)
	})
	return file_contents_v1_tag_proto_rawDescData
}

var file_contents_v1_tag_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contents_v1_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_contents_v1_tag_proto_goTypes = []interface{}{
	(TagGetMultipleRequest_SortDirection)(0), // 0: contents.v1.TagGetMultipleRequest.SortDirection
	(*Tag)(nil),                              // 1: contents.v1.Tag
	(*TagCreateUpdate)(nil),                  // 2: contents.v1.TagCreateUpdate
	(*TagGetOneRequest)(nil),                 // 3: contents.v1.TagGetOneRequest
	(*TagGetOneResponse)(nil),                // 4: contents.v1.TagGetOneResponse
	(*TagGetMultipleRequest)(nil),            // 5: contents.v1.TagGetMultipleRequest
	(*TagGetMultipleResponse)(nil),           // 6: contents.v1.TagGetMultipleResponse
	(*TagCreateRequest)(nil),                 // 7: contents.v1.TagCreateRequest
	(*TagCreateResponse)(nil),                // 8: contents.v1.TagCreateResponse
	(*TagUpdateRequest)(nil),                 // 9: contents.v1.TagUpdateRequest
	(*TagUpdateResponse)(nil),                // 10: contents.v1.TagUpdateResponse
	(*TagDeleteRequest)(nil),                 // 11: contents.v1.TagDeleteRequest
	(*TagDeleteResponse)(nil),                // 12: contents.v1.TagDeleteResponse
}
var file_contents_v1_tag_proto_depIdxs = []int32{
	1, // 0: contents.v1.TagGetOneResponse.data:type_name -> contents.v1.Tag
	0, // 1: contents.v1.TagGetMultipleRequest.sort_by:type_name -> contents.v1.TagGetMultipleRequest.SortDirection
	1, // 2: contents.v1.TagGetMultipleResponse.data:type_name -> contents.v1.Tag
	2, // 3: contents.v1.TagCreateRequest.data:type_name -> contents.v1.TagCreateUpdate
	1, // 4: contents.v1.TagCreateResponse.data:type_name -> contents.v1.Tag
	2, // 5: contents.v1.TagUpdateRequest.data:type_name -> contents.v1.TagCreateUpdate
	1, // 6: contents.v1.TagUpdateResponse.data:type_name -> contents.v1.Tag
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_contents_v1_tag_proto_init() }
func file_contents_v1_tag_proto_init() {
	if File_contents_v1_tag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contents_v1_tag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_tag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagCreateUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_tag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagGetOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_tag_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagGetOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_tag_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagGetMultipleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_tag_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagGetMultipleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_tag_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_tag_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_tag_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_tag_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_tag_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contents_v1_tag_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contents_v1_tag_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contents_v1_tag_proto_goTypes,
		DependencyIndexes: file_contents_v1_tag_proto_depIdxs,
		EnumInfos:         file_contents_v1_tag_proto_enumTypes,
		MessageInfos:      file_contents_v1_tag_proto_msgTypes,
	}.Build()
	File_contents_v1_tag_proto = out.File
	file_contents_v1_tag_proto_rawDesc = nil
	file_contents_v1_tag_proto_goTypes = nil
	file_contents_v1_tag_proto_depIdxs = nil
}
